# Generated by Django 5.0.7 on 2026-07-01 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_task_actual_end_task_actual_start_task_delay_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='wbs_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
