# Generated by Django 5.0.7 on 2026-06-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='meslek_rolu',
            field=models.CharField(blank=True, choices=[('ELK', 'Elektrik/Otomasyon Müh.'), ('PLC', 'PLC Programcısı'), ('SCADA', 'SCADA Mühendisi'), ('SAHA', 'Saha Teknisyeni'), ('PM', 'Proje Müdürü')], default='', max_length=10),
        ),
    ]
