# Generated by Django 5.0.7 on 2026-06-29 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_bildirim'),
        ('projects', '0002_task_actual_end_task_actual_start_task_delay_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('tax_number', models.CharField(blank=True, max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Müteahhit Profili',
                'verbose_name_plural': 'Müteahhit Profilleri',
            },
        ),
        migrations.CreateModel(
            name='ProjectContractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100)),
                ('contract_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_projects', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractors', to='projects.project')),
            ],
            options={
                'verbose_name': 'Proje Müteahhiti',
                'verbose_name_plural': 'Proje Müteahhitleri',
                'unique_together': {('project', 'contractor')},
            },
        ),
    ]
