# Generated by Django 5.0.7 on 2026-07-01 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_task_parent_task_wbs_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50)),
                ('supplier_name', models.CharField(max_length=255)),
                ('supplier_contact', models.CharField(blank=True, max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(default='TRY', max_length=3)),
                ('order_date', models.DateField()),
                ('expected_delivery', models.DateField()),
                ('actual_delivery', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('partial', 'Kısmi Teslim'), ('delivered', 'Teslim Edildi'), ('cancelled', 'İptal')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='projects.project')),
            ],
            options={
                'verbose_name': 'Satın Alma Siparişi',
                'verbose_name_plural': 'Satın Alma Siparişleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('quantity_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('inspection_status', models.CharField(choices=[('pending', 'Bekliyor'), ('passed', 'Kabul'), ('rejected', 'Red')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='procurement.purchaseorder')),
            ],
            options={
                'verbose_name': 'Malzeme Teslimi',
                'verbose_name_plural': 'Malzeme Teslimleri',
                'ordering': ['-delivery_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit', models.CharField(default='adet', max_length=50)),
                ('required_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('approved', 'Onaylandı'), ('ordered', 'Sipariş Verildi'), ('delivered', 'Teslim Alındı'), ('cancelled', 'İptal')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='projects.project')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Satın Alma Talebi',
                'verbose_name_plural': 'Satın Alma Talepleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='procurement.purchaserequest'),
        ),
    ]
