# Generated by Django 5.0.7 on 2026-06-29 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_task_actual_end_task_actual_start_task_delay_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('PERSONNEL', 'Personel'), ('EQUIPMENT', 'Ekipman'), ('MATERIAL', 'Malzeme')], max_length=20)),
                ('unit', models.CharField(default='adet', max_length=50)),
                ('capacity_per_day', models.DecimalField(decimal_places=2, default=8, max_digits=10)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Kaynak',
                'verbose_name_plural': 'Kaynaklar',
                'ordering': ['resource_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TaskResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='resources.resource')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='projects.task')),
            ],
            options={
                'verbose_name': 'Görev Kaynağı',
                'verbose_name_plural': 'Görev Kaynakları',
                'unique_together': {('task', 'resource')},
            },
        ),
    ]
