# Generated by Django 5.0.7 on 2026-07-01 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_task_parent_task_wbs_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HSEInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField()),
                ('findings', models.TextField()),
                ('action_required', models.TextField(blank=True)),
                ('next_inspection_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Açık'), ('closed', 'Kapalı')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hse_inspections', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hse_inspections', to='projects.project')),
            ],
            options={
                'verbose_name': 'İSG Denetimi',
                'verbose_name_plural': 'İSG Denetimleri',
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkAccident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident_date', models.DateField()),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('near_miss', 'Ramak Kala'), ('minor', 'Hafif'), ('major', 'Ağır'), ('fatal', 'Ölümlü')], default='near_miss', max_length=20)),
                ('injured_person', models.CharField(blank=True, max_length=255)),
                ('action_taken', models.TextField(blank=True)),
                ('reported_to_sgk', models.BooleanField(default=False)),
                ('sgk_report_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_accidents', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accidents', to='projects.project')),
            ],
            options={
                'verbose_name': 'İş Kazası',
                'verbose_name_plural': 'İş Kazaları',
                'ordering': ['-accident_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('worker_count', models.PositiveIntegerField(default=0)),
                ('subcontractor_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_entries', to='projects.project')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'İşçi Giriş Kaydı',
                'verbose_name_plural': 'İşçi Giriş Kayıtları',
                'ordering': ['-date'],
            },
        ),
    ]
