# Generated by Django 5.0.7 on 2026-07-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punchlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punchitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='punchitem',
            name='no',
            field=models.CharField(blank=True, help_text='FAT-001 vb. otomatik atanır', max_length=20),
        ),
        migrations.AlterField(
            model_name='punchitem',
            name='tespit_tarihi',
            field=models.DateField(blank=True, help_text='Test sırasında tespit tarihi', null=True),
        ),
    ]
