# Generated by Django 5.0.7 on 2026-07-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='etki',
            field=models.PositiveSmallIntegerField(default=3, help_text='1=Önemsiz … 5=Kritik'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='mitigasyon',
            field=models.TextField(blank=True, help_text='Azaltma / önlem planı'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='olasilik',
            field=models.PositiveSmallIntegerField(default=3, help_text='1=Çok Düşük … 5=Çok Yüksek'),
        ),
    ]
