# Generated by Django 5.0.7 on 2026-06-21 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('plc_scada', 'PLC/SCADA'), ('robot', 'Robot Sistemleri'), ('mes', 'MES'), ('vizyon', 'Vizyon Sistemi'), ('elektrik', 'Elektrik Altyapı'), ('servo', 'Servo/Hareket'), ('genel', 'Genel')], default='genel', max_length=20)),
                ('file', models.FileField(upload_to='techdocs/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tech_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teknik Döküman',
                'verbose_name_plural': 'Teknik Dökümanlar',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
