# Generated by Django 5.0.7 on 2026-06-21 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_technicaldocument'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('spec_type', models.CharField(choices=[('plc_scada', 'PLC/SCADA'), ('robot', 'Robot Sistemleri'), ('mes', 'MES'), ('vizyon', 'Vizyon Sistemi'), ('elektrik', 'Elektrik Altyapı'), ('servo', 'Servo/Hareket'), ('genel', 'Genel')], default='genel', max_length=20)),
                ('customer', models.CharField(blank=True, max_length=255)),
                ('contract_no', models.CharField(blank=True, max_length=100)),
                ('revision', models.CharField(default='Rev.0', max_length=20)),
                ('status', models.CharField(choices=[('taslak', 'Taslak'), ('inceleme', 'İncelemede'), ('onaylı', 'Onaylı'), ('revize', 'Revize')], default='taslak', max_length=20)),
                ('scope', models.TextField(blank=True)),
                ('standards', models.TextField(blank=True)),
                ('system_requirements', models.TextField(blank=True)),
                ('hardware_specs', models.TextField(blank=True)),
                ('software_specs', models.TextField(blank=True)),
                ('communication', models.TextField(blank=True)),
                ('acceptance_tests', models.TextField(blank=True)),
                ('documentation_req', models.TextField(blank=True)),
                ('training_warranty', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specs', to='projects.project')),
            ],
            options={
                'verbose_name': 'Teknik Şartname',
                'verbose_name_plural': 'Teknik Şartnameler',
                'ordering': ['-updated_at'],
            },
        ),
    ]
