# Generated by Django 5.0.7 on 2026-06-29 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_eplandokuman'),
        ('projects', '0002_task_actual_end_task_actual_start_task_delay_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='site_photos/%Y/%m/')),
                ('description', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_photos', to='projects.project')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saha Fotoğrafı',
                'verbose_name_plural': 'Saha Fotoğrafları',
                'ordering': ['-taken_at', '-uploaded_at'],
            },
        ),
    ]
