# Generated by Django 5.0.7 on 2026-07-01 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_sitephoto'),
        ('projects', '0003_task_parent_task_wbs_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_type', models.CharField(choices=[('yapi_ruhsati', 'Yapı Ruhsatı'), ('cevre_izni', 'Çevre İzni'), ('isg_belgesi', 'İSG Belgesi'), ('belediye_onayi', 'Belediye Onayı'), ('diger', 'Diğer')], max_length=20)),
                ('permit_no', models.CharField(max_length=100)),
                ('issued_by', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('expired', 'Süresi Dolmuş'), ('pending_renewal', 'Yenileme Bekliyor')], default='active', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='permits/%Y/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permits', to='projects.project')),
            ],
            options={
                'verbose_name': 'Yasal İzin/Ruhsat',
                'verbose_name_plural': 'Yasal İzinler/Ruhsatlar',
                'ordering': ['expiry_date'],
            },
        ),
    ]
