# Generated by Django 5.0.7 on 2026-07-01 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_task_parent_task_wbs_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('RFI', 'Teknik Talep (RFI)'), ('DCN', 'Tasarım Değişik. (DCN)'), ('letter', 'Resmi Yazı'), ('memo', 'İç Yazışma'), ('transmittal', 'Transmittal')], max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('from_party', models.CharField(max_length=255)),
                ('to_party', models.CharField(max_length=255)),
                ('sent_at', models.DateField()),
                ('response_due', models.DateField(blank=True, null=True)),
                ('responded_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Açık'), ('responded', 'Yanıtlandı'), ('closed', 'Kapalı'), ('overdue', 'Gecikmiş')], default='open', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondences', to='projects.project')),
            ],
            options={
                'verbose_name': 'Yazışma',
                'verbose_name_plural': 'Yazışmalar',
                'ordering': ['-sent_at'],
            },
        ),
    ]
