# Generated by Django 5.0.7 on 2026-07-01 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_task_parent_task_wbs_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_plans', to='projects.project')),
            ],
            options={
                'verbose_name': 'Muayene Planı',
                'verbose_name_plural': 'Muayene Planları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=255)),
                ('hold_point_type', models.CharField(choices=[('H', 'Hold'), ('W', 'Witness'), ('R', 'Review')], default='W', max_length=1)),
                ('responsible_party', models.CharField(blank=True, max_length=255)),
                ('standard_ref', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('passed', 'Geçti'), ('failed', 'Kaldı'), ('waived', 'Muaf')], default='pending', max_length=20)),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('result_notes', models.TextField(blank=True)),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quality.inspectionplan')),
            ],
            options={
                'verbose_name': 'Muayene Kalemi',
                'verbose_name_plural': 'Muayene Kalemleri',
                'ordering': ['activity_name'],
            },
        ),
        migrations.CreateModel(
            name='NCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncr_no', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('minor', 'Minör'), ('major', 'Majör'), ('critical', 'Kritik')], default='minor', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Açık'), ('in_progress', 'İşlemde'), ('closed', 'Kapalı'), ('accepted', 'Kabul Edildi')], default='open', max_length=20)),
                ('action_plan', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_ncrs', to=settings.AUTH_USER_MODEL)),
                ('inspection_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quality.inspectionitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ncrs', to='projects.project')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raised_ncrs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uygunsuzluk Raporu',
                'verbose_name_plural': 'Uygunsuzluk Raporları',
                'ordering': ['-created_at'],
            },
        ),
    ]
