# Generated by Django 5.0.7 on 2026-06-22 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoleSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_id', models.CharField(max_length=20, unique=True)),
                ('rol_adi', models.CharField(max_length=100)),
                ('renk_kodu', models.CharField(default='#4f6ef7', max_length=7)),
                ('ikon', models.CharField(blank=True, max_length=10)),
                ('sorumluluklar', models.JSONField(default=list)),
                ('yetkinlikler', models.JSONField(default=list)),
                ('skill_icerik', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Rol Skill',
                'verbose_name_plural': "Rol Skill'leri",
                'ordering': ['rol_adi'],
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gorev_id_prefix', models.CharField(max_length=10)),
                ('gorev_sira', models.PositiveSmallIntegerField(default=0)),
                ('gorev_adi', models.CharField(max_length=200)),
                ('faz', models.CharField(choices=[('Başlangıç', 'Başlangıç'), ('Planlama', 'Planlama'), ('Hazırlık', 'Hazırlık'), ('Tasarım', 'Tasarım'), ('Tedarik', 'Tedarik'), ('Geliştirme', 'Geliştirme'), ('Kurulum', 'Kurulum'), ('Entegrasyon', 'Entegrasyon'), ('Test', 'Test'), ('Devreye Alma', 'Devreye Alma'), ('Kabul', 'Kabul'), ('Yürütme', 'Yürütme'), ('Kapanış', 'Kapanış')], max_length=30)),
                ('min_gun', models.DecimalField(decimal_places=1, max_digits=4)),
                ('max_gun', models.DecimalField(decimal_places=1, max_digits=4)),
                ('onkosullar', models.JSONField(default=list)),
                ('teslimati', models.CharField(blank=True, max_length=255)),
                ('tekrar', models.CharField(blank=True, max_length=20)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gorev_sablonlari', to='skills.roleskill')),
            ],
            options={
                'verbose_name': 'Görev Şablonu',
                'verbose_name_plural': 'Görev Şablonları',
                'ordering': ['rol', 'gorev_sira'],
            },
        ),
    ]
