# Generated by Django 5.0.7 on 2026-06-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GorevDurumu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deger', models.CharField(max_length=30, unique=True)),
                ('renk', models.CharField(max_length=7)),
                ('ikon', models.CharField(blank=True, max_length=10)),
                ('sira', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Görev Durumu',
                'verbose_name_plural': 'Görev Durumları',
                'ordering': ['sira'],
            },
        ),
        migrations.AddField(
            model_name='roleskill',
            name='durum_alanlari',
            field=models.JSONField(default=list),
        ),
    ]
