# Generated by Django 5.0.7 on 2026-07-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iopoint',
            name='alan_cihaz',
            field=models.CharField(blank=True, help_text='Saha enstrümanı/cihaz', max_length=150),
        ),
        migrations.AlterField(
            model_name='iopoint',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='iopoint',
            name='panel_no',
            field=models.CharField(blank=True, help_text='Panel/MCC numarası', max_length=30),
        ),
        migrations.AlterField(
            model_name='iopoint',
            name='plc_kanal',
            field=models.CharField(blank=True, help_text='Kanal numarası', max_length=20),
        ),
        migrations.AlterField(
            model_name='iopoint',
            name='plc_rack',
            field=models.CharField(blank=True, help_text='Rack numarası', max_length=20),
        ),
        migrations.AlterField(
            model_name='iopoint',
            name='plc_slot',
            field=models.CharField(blank=True, help_text='Slot numarası', max_length=20),
        ),
        migrations.AlterField(
            model_name='iopoint',
            name='proses_deger',
            field=models.CharField(blank=True, help_text='4-20mA, 0-10V, NC/NO vb.', max_length=100),
        ),
        migrations.AlterField(
            model_name='iopoint',
            name='sil_seviye',
            field=models.CharField(blank=True, help_text='SIL 1/2/3 veya boş', max_length=10),
        ),
        migrations.AlterField(
            model_name='iopoint',
            name='tag_no',
            field=models.CharField(help_text='FIC-101, LSH-201 vb.', max_length=50),
        ),
        migrations.AlterField(
            model_name='iopoint',
            name='tanim',
            field=models.CharField(help_text='Etiket açıklaması', max_length=255),
        ),
    ]
