# Generated by Django 5.0.7 on 2026-07-01 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_task_parent_task_wbs_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_number', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('reason', models.CharField(choices=[('scope', 'Kapsam Değişikliği'), ('design', 'Tasarım Değişikliği'), ('client_request', 'Müşteri Talebi'), ('unforeseen', 'Öngörülemeyen Durum'), ('other', 'Diğer')], default='other', max_length=20)),
                ('cost_impact', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('schedule_impact_days', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('submitted', 'Gönderildi'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cos', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_orders', to='projects.project')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_cos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Değişiklik Emri',
                'verbose_name_plural': 'Değişiklik Emirleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
