# Generated by Django 5.0.7 on 2026-06-29 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_task_actual_end_task_actual_start_task_delay_reason_and_more'),
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('planned_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('submitted', 'Gönderildi'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='projects.project')),
            ],
            options={
                'verbose_name': 'Hakediş',
                'verbose_name_plural': 'Hakedişler',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('hours_worked', models.DecimalField(decimal_places=2, default=8, max_digits=5)),
                ('work_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('submitted', 'Gönderildi'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_timesheets', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='projects.project')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheets', to='resources.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Puantaj',
                'verbose_name_plural': 'Puantajlar',
                'ordering': ['-work_date'],
            },
        ),
    ]
