# Generated by Django 5.0.7 on 2026-07-01 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiyatFarki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endeks_turu', models.CharField(max_length=100)),
                ('baslangic_endeksi', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('bitis_endeksi', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('fark_tutari', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('progress_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiyat_farklari', to='payroll.progresspayment')),
            ],
            options={
                'verbose_name': 'Fiyat Farkı',
                'verbose_name_plural': 'Fiyat Farkları',
            },
        ),
        migrations.CreateModel(
            name='MetrajSatiri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poz_no', models.CharField(max_length=50)),
                ('tanim', models.CharField(max_length=255)),
                ('birim', models.CharField(max_length=20)),
                ('sozlesme_miktari', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('gerceklesen_miktar', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('birim_fiyat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('progress_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metraj_satirlari', to='payroll.progresspayment')),
            ],
            options={
                'verbose_name': 'Metraj Satırı',
                'verbose_name_plural': 'Metraj Satırları',
                'ordering': ['poz_no'],
            },
        ),
    ]
