# Generated by Django 5.0.7 on 2026-07-01 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('iscilik', 'İşçilik'), ('malzeme', 'Malzeme'), ('ekipman', 'Ekipman'), ('taseron', 'Taşeronluk'), ('genel_gider', 'Genel Gider'), ('diger', 'Diğer')], default='diger', max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('planned_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='budget.budget')),
            ],
            options={
                'verbose_name': 'Bütçe Kalemi',
                'verbose_name_plural': 'Bütçe Kalemleri',
                'ordering': ['category', 'description'],
            },
        ),
    ]
